version: "3.1"

services:
  server:
    build: ./server
    command: sh -c "bundle exec rackup --host 0.0.0.0 -p 4567"
    working_dir: /app
    ports:
      - 4567:4567
    volumes:
      - ./server:/app

  client:
    build: ./client
    command: /usr/src/app/entrypoint.sh prod
    working_dir: /usr/src/app
    links:
      - server
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
